### ISSUE TITLE
Windows version ? 64 bits Java version ?

### ISSUE THREAD

**Issue by SebCanet** [damellis/A4S#12]
Hi,
I tried A4S on Windows but everything is in 64 bits.
I tried installing the 32bit version of Java, and use this command line :
java -d64 -jar A4S.jar COM3

and Windows says :
java.lang.UnsatisfiedLinkError: S:\Travail\PAF\exemples_scratch\Scratch2_et_Ardu
ino\A4S\rxtxSerial.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform throw
n while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: S:\Travail\PAF\exempl
es_scratch\Scratch2_et_Arduino\A4S\rxtxSerial.dll: Can't load IA 32-bit .dll on
a AMD 64-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
        at A4S.main(A4S.java:76)

If I try :
java -d32 -jar A4S.jar COM3
I have :
Error: This Java instance does not support a 32-bit JVM.
Please install the desired version.

Can I run it on Windows and Scratch 2 ?
Thanks a lot.

**Comment by al-alamin** [comment]
damellis thanx man

**Comment by Elliott-Green** [comment]
Damellis, saving my life with that dll. 100% working for 64 bit windows systems 7+8.

**Comment by vinuvish** [comment]
bro im getting this error 
win32com.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform

**Comment by MousaAlfhaily** [comment]
Thanks a lot, it's working after a lot of searching.
but seriously, Oracle should make this a lot easier to use COMs, and add it without having to do that manually.

**Comment by SergioMP** [comment]
Thanks @damellis!  Downloading the x64 rxtxSerial.dll from the link you posted and putting such file on the project source directory did the trick! I was getting the same error than @vinuvish, and that solved it.
